package devices.zeroshot.qwen;

/*
This class was generated by 'qwen'

Q: Provide an implementation for this java interface of a Device: "public interface Device {
    void on() throws IllegalStateException;
    void off();
    boolean isOn();
    void reset();
}
"
*/

import devices.Device;

//A:
public class LightSwitch implements Device {
    private boolean isOn;
    
    public LightSwitch() {
        this.isOn = false;
    }
    
    @Override
    public void on() throws IllegalStateException {
        if (isOn) {
            throw new IllegalStateException("Device is already on.");
        }
        isOn = true;
    }
    
    @Override
    public void off() {
        isOn = false;
    }
    
    @Override
    public boolean isOn() {
        return isOn;
    }
    
    @Override
    public void reset() {
        isOn = false;
    }
}
